name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno fmt --check

      - run: deno check src/mod.ts

      - name: Test
        run: deno test

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci

      - name: Build
        run: npm run build